// import Head from "next/head";
// import dynamic from "next/dynamic";

// var Editor = dynamic(() => import("@/components/CKEditor"), {
// 	ssr: false,
// });

// export default function Home() {
// 	return (
// 		<div className="home">
// 			<Head>
// 				<title>T4technow</title>
// 				<meta name="description" content="Generated by create next app" />
// 				<link rel="icon" href="/favicon.ico" />
// 			</Head>

// 			<main>
// 				<div style={{ height: "400px" }}>
// 					<Editor />
// 				</div>
// 			</main>
// 		</div>
// 	);
// }

import React from "react";

const Index = () => {
	return <div>Index</div>;
};

export default Index;
